[package]
name = "radar-server"
edition = "2024"
version = "0.1.0"
license = "GPL-3.0-only"
description = "Server component of example:radar, a Pumpkin plugin"

[lib]
crate-type = ["cdylib"]

[dependencies]
pumpkin-plugin-api = { path = "../../../third_party/pumpkin/crates/pumpkin-plugin-api" }
radar-protocol = { path = "../protocol" }
tracing = "0.1"

[profile.release]
opt-level = "s"
lto = true
strip = true

[workspace]
